/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    region: 'us-west-2',
    bucket: 'sll-dicom-store',
    identityPoolId: 'us-west-2:1fd67970-29aa-4ea4-97cd-12dc377e66b0',
    aws_project_region: 'us-west-2',
    aws_cognito_identity_pool_id: 'us-west-2:1fd67970-29aa-4ea4-97cd-12dc377e66b0',
    aws_cognito_region: 'us-west-2',
    aws_user_pools_id: 'us-west-2_bEKqkurBi',
    aws_user_pools_web_client_id: '216cjja3a91m44j1n2jkl8pbn',
    oauth: {},
    aws_cognito_username_attributes: ['EMAIL'],
    aws_cognito_social_providers: [],
    aws_cognito_signup_attributes: ['EMAIL'],
    aws_cognito_mfa_configuration: 'OFF',
    aws_cognito_mfa_types: ['SMS'],
    aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: [],
    },
    aws_cognito_verification_mechanisms: ['EMAIL'],
};

export default awsmobile;
